### ISSUE TITLE
PaymentApp/build.gradle' does not exist.

### ISSUE THREAD

**Issue by vhpoet** [Shopify/interledger-payment-app-example#1]
Followed all of your steps, and I get `PaymentApp/build.gradle' does not exist.` when running `./bin/setup_emulator`. Am I missing something @Krystosterone?

**Comment by Krystosterone** [comment]
Ah you're totally right, `*.gradle` is not versioned as per: https://github.com/Shopify/interledger-payment-app-example/blob/master/.gitignore#L2. 

I've pushed a commit to fix the `.gitignore`; it should now be included. See: 2ad3eeef86d4aa77646e537a4bbf922c9a14554e
